unit TestAreaAggegator;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, uAreaAggegator, SysUtils, Classes, uShapes;

type
    TestTAreaAggregator = class(TTestCase)
    private
        FAreaAggregator: TAreaAggregator;
    public
        procedure SetUp; override;
        procedure TearDown; override;
    published
        procedure TestSumArea_ZeroShapes;
        procedure TestSumArea_OneRectangle;
        procedure TestSumArea_TwoRectangles;
        procedure TestSumArea_ThreeRectangles;
    end;

implementation

procedure TestTAreaAggregator.SetUp;
begin
    FAreaAggregator := TAreaAggregator.Create;
end;

procedure TestTAreaAggregator.TearDown;
begin
    FAreaAggregator.Free;
    FAreaAggregator := nil;
end;

procedure TestTAreaAggregator.TestSumArea_ZeroShapes;
var
    ReturnValue: Double;
begin
    ReturnValue := FAreaAggregator.SumArea([]);

    CheckEquals(0, ReturnValue);
end;

procedure TestTAreaAggregator.TestSumArea_OneRectangle;
var
    ReturnValue: Double;
    R1: TRectangle;
begin
    R1 := TRectangle.Create(3, 4);
    try
        ReturnValue := FAreaAggregator.SumArea([R1]);
    finally
        R1.Free;
    end;

    CheckEquals(12, ReturnValue);
end;

procedure TestTAreaAggregator.TestSumArea_TwoRectangles;
var
    ReturnValue: Double;
    R1, R2: TRectangle;
begin
    R1 := TRectangle.Create(3, 4);
    R2 := TRectangle.Create(8, 2);
    try
        ReturnValue := FAreaAggregator.SumArea([R1, R2]);
    finally
        R1.Free;
        R2.Free;
    end;

    CheckEquals(28, ReturnValue);
end;

procedure TestTAreaAggregator.TestSumArea_ThreeRectangles;
var
    ReturnValue: Double;
    R1, R2, R3: TRectangle;
begin
    R1 := TRectangle.Create(3, 4);
    R2 := TRectangle.Create(8, 2);
    R3 := TRectangle.Create(5, 6);
    try
        ReturnValue := FAreaAggregator.SumArea([R1, R2, R3]);
    finally
        R1.Free;
        R2.Free;
        R3.Free;
    end;

    CheckEquals(58, ReturnValue);
end;

initialization

  RegisterTest(TestTAreaAggregator.Suite);

end.

